# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Leandrosa81.TaskbarMonitor
PackageVersion: 0.4.1
PackageLocale: en-US
Publisher: Leandrosa81
PackageName: TaskbarMonitor
License: GPL 3.0
Copyright: Copyright ©  2020
ShortDescription: monitoring tool with graphs (CPU, memory, disk and network) for Windows taskbar.
ManifestType: defaultLocale
ManifestVersion: 1.2.0

